##
##  Makefile -- Build procedure for sample negotiation_device Apache module
##  Autogenerated via ``apxs -n negotiation_device -g''.
##

builddir=.
top_srcdir=/usr/share/apache2
top_builddir=/usr/share/apache2
include /usr/share/apache2/build/special.mk

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib

#   the default target
all: mod_negotiation_device.la

mod_negotiation_device.la: mod_negotiation_device.slo mobile_detect.slo

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_negotiation_device.o mod_negotiation_device.lo mod_negotiation_device.slo mod_negotiation_device.la mobile_detect.o

#   simple test
test: reload
	lynx -mime_header http://localhost/negotiation_device

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

